### ISSUE TITLE
Invitation manager

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#467]
## Invitation email

- [ ] Update the URL on the call to action behind the `JOIN NOW` button: `https://labelflow.ai/[workspace-slug]/accept-invite?invitationToken=yy`
  - [ ] invitation token is a uuid

## Invitation manager

- [ ] Create following pages
  - [ ] Accept/Decline membership page.
  - [ ] This invitation is not valid
  - [ ] This invitation was already accepted
- [ ] Implement invitation manager state diagram [here in figma](https://www.figma.com/file/56hJc9jl9oedCWIfxj7TyU/State-Diagram?node-id=0%3A1)

## State diagram

![image](https://user-images.githubusercontent.com/16015322/137160844-bde9c108-e108-421a-8ab3-eea911314292.png)

## Mockup
[Accept/Decline invitation](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3317%3A18876)
[Revoked invitation](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3317%3A18877)
[Already accepted](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3318%3A19010)

  
Blocked by #463
Blocked by #461

**Comment by RaynalHugo** [comment]
As we discussed during the DSM, I want to clear a bit the invitation status potential states.

Here are the possible states before my MR. They can be returned by the `inviteMember` mutation.

```graphql
enum InvitationStatus {
  Sent
  UserAlreadyIn
  Error
}
```

I think I need to have the following states

```graphql
enum InvitationStatus {
  Sent
  UserAlreadyIn
  Error
  Active
  Declined
  Expired
  Revoked
}
```

## Hypothesis

- On the page `https://labelflow.ai/[workspace-slug]/accept-invite?invitationToken=XX`, we perform a query:

```graphql
membership(where: {invitationToken: $invitationToken}){
    id
    invitationStatus
}
```

- From this query, if it returns no membership, we display the "Invitation is not valid" state.
- If it returns a membership, the message depends on the `invitationStatus`.
- I will add 2 new resolvers: `acceptInvite` and `declineInvite`. Those resolvers will also perform server-side validation checks before accepting the change. The `invitationStatus` will be used to inform the user on the `/../accept-invite` page as well as on the membership table.

## States

- **Sent**:
  - Membership isn't already linked to a user
  - Membership has an invitation token
  - Membership isn't UserAlreadyIn, Expired, Declined, Expired or Revoked
- **UserAlreadyIn**:  
  Comes from the `inviteMember` mutation. It has strange behaviour here. Should it depend on the user performing the query? Or is there a better way to do/name this? **(1)** It would make sense to use this to prevent a user already in the workspace to try to accept an invite for this workspace.
  - Membership isn't already linked to a user
  - Membership has an invitation token
  - User performing the query is already member of this workspace.
- **Error**:  
   Can't be returned in the `membership.invitationStatus` resolver. It's only useful for the `inviteMember` mutation.
- **Active**:
  - Membership is linked to a user
- **Declined**:
  - Membership has a value for `declinedAt`? **(2)**
- **Expired**:
  - Membership isn't already linked to a user
  - Membership has an invitation token
  - Current date is passed the value for `Membership.invitationExpiresAt`? Or current date is passed the value for `Membership.createdAt` + an existing hardcoded duration? **(3)**
- **Revoked**:  
  Do we really want this state? Does it make sense to differentiate this from a non-existing membership? **(4)** Also, should I make it impossible to revoke an invitation after it has been accepted. **(5)**
  - Membership has a value for `revokedAt`? **(6)**

## Additional Questions

_I marked my previous questions directly above like this_ **(1)**.

7. Should I split the enum `InvitationStatus` into 2?
   - 1 enum for the output of the `inviteMember` mutation
   - 1 other enum for the potential states of a membership.
8. Should we remove the `invitationToken` from the `Membership` once it's accepted?
9. Should I implement a `revokedInvitation` mutation?
10. Some states may not be required in order to have a working MVP (Expired, Revoked). Should I implement all those states in this MR? I think I could deliver an MVP faster if I don't, but I think it won't be really complex to add them all at once.

**Comment by RaynalHugo** [comment]
- split enums
```graphql
enum InvitationResult {
  Sent
  UserAlreadyIn
  Error
}
```

```graphql
enum MembershipStatus {
  Sent
  Active
  Declined
}

enum CurrentUserCanAccept {
   Yes,
   AlreadyAccepted,
   AlreadyMemberOfTheWorkspace,
   AlreadyDeclined,
}
```


- use membership id instead of invitation token
- don't revoke, have an explicit message like "this invitation isn't valid or has been revoked"

**Comment by RaynalHugo** [comment]
Related PR has been merged on the feature branch
