### ISSUE TITLE
Upload of files > 5Mb not supported on vercel

### ISSUE THREAD

**Issue by crubier** [labelflow/labelflow#576]
Once deployed on Vercel, we hit a "5MB upload limit" which I didnt know about.... 

`Request Entity Too Large FUNCTION_PAYLOAD_TOO_LARGE` 

See https://vercel.com/support/articles/how-to-bypass-vercel-5mb-body-size-limit-serverless-functions. 

I think the solution would be to make the upload go directly to supabase, but I dont think it's possible for uploads... Probably need to open an issue on supabase: Need to be able to create a SignedUrl for UPload. 

<img width="1499" alt="Screenshot 2021-11-12 at 17 06 38" src="https://user-images.githubusercontent.com/2954572/141507173-5c87bdea-df59-415e-98f3-38ee00f3d966.png">

Blocked by #607

**Comment by etiennedupont** [comment]
I started investigating the issue. Here are the options I envision:
- Wait for an upload signedUrl on Supabase as Vincent proposed, since it doesn’t exist yet => the easiest alternative if we're not in a hurry
- Use the Supabase client, client-side. We'd need to give extra care about security, and the fact we don’t use Supabase auth is not helping. Some references to do that: https://supabase.io/docs/guides/auth#row-level-security & https://github.com/supabase/supabase/tree/master/examples/nextjs-ts-user-management#postgres-row-level-security
- Use another storage method (Google Cloud, AWS) that supports upload SignedUrl, in an end-to-end fashion instead of Supabase => Probably the best option if we want to move fast
- Use another storage method (Google Cloud, AWS) as an intermediate. E.g. upload on a GC bucket then download it from the API serverless function and finally upload on Supabase using the client => makes things more intricate

**Comment by RaynalHugo** [comment]
> * Wait for an upload signedUrl on Supabase as Vincent proposed, since it doesn’t exist yet => the easiest alternative if we're not in a hurry

Oh I was sure it existed but I've just seen that it's only for download, and not for upload ...

**Comment by etiennedupont** [comment]
Issue created on Supabase
https://github.com/supabase/storage-api/issues/81

**Comment by etiennedupont** [comment]
Fixed in #607
