### ISSUE TITLE
Deploy the schema in the CI

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#584]
## Objectives
Allow to deploy automatically new schema

## Tasks

- [ ] CI need another port to connect directly to postgres (and bypass pgbouncer): https://community.redwoodjs.com/t/guide-migrations-connection-pool-urls-supabase/2505
- [ ] Follow prisma documentation for the good practice on how to deploy it in the CI (@RaynalHugo for the link to the doc)

Blocked by #621

**Comment by RaynalHugo** [comment]
After further investigation, I think we would need to do this when we will merge #497. 

As advised in Prisma's documentation ([here](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-vercel/)), it is recommended to do this directly in Vercel. 
I found this counter-intuitive at first, but it makes sense. This way, our Next.js deployment is always in sync with the backend deployment. 

A small change I could see compare to the doc is to run `next build && prisma generate && prisma migrate deploy` instead of `prisma generate && prisma migrate deploy && next build`. This way, we don't deploy the schema changes if the next app fails to build.

As for not doing it now, if we do this, every time we merge something on `main`, it will complain as the Prisma schema is more advanced on the workspace feature branch and we use the same database for developments see (#523).

**Comment by nacho-carnicero** [comment]
Something to take into account here as well is that we need to use a different endpoint for applying migrations to the DB than the endpoint that prisma uses for connecting through PGBouncer to the DB. Indeed, Prisma needs direct access to the DB to apply the migration, otherwise it will fail.

We can follow [this guide](https://community.redwoodjs.com/t/guide-migrations-connection-pool-urls-supabase/2505) to have something working

**Comment by RaynalHugo** [comment]
Yes, this guide is the issue description ;) 

I think I will already implement the change and use the latest tip to avoid deploying on PR, but also on main. This way we will just need to add an env var when we will want the automatic deployment of schema changes .
