### ISSUE TITLE
Add spinner on the Label Class page. Investigate on filtering/search not working.

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#665]
- [x] Stress test, behavior with 100, 300, 1000 classes? Works well with 402 classes
- [x] Query the complete list of classes, one unique query
- [x] The entire page is taking some time to load. Add a spinner to show that the data is loading
- [x] Investigate the filtering issues on the search field of the class selection menus.

**Comment by nicOwlas** [comment]
@Jordanlelay @valerian the class list remains fluid even with 402 classes :+1: 

Some issues though (I'll edit the issue correspondingly):
- It takes a few seconds to load the list, we need to add a spinner to show it is loading
- The reordering of the classes remains very usable (small delay at the beginning but nothing blocking)
- Problem: in the labeling view, the search is failing in the class component. The filtering is not working anymore.

Recording

https://user-images.githubusercontent.com/16015322/146932681-24d14723-1402-47a4-804f-67522fc0fe1a.mov

:

**Comment by Jordanlelay** [comment]
@nicOwlas If the search does not work, I think it's because you have several classes with the same name. I have created 400 classes with different names and the search keeps working (it's a bit slow). If you have 2 classes with the same name, all sort of problems start appearing. Because we give React a reference to the list element in the popover to the class by its name, having several times the same name produces errors. You should retry the search with 400 uniques elements if the problem persist, I will investigate more.

I'm assuming that 2 classes **cannot** have identical names inside the same dataset
