### ISSUE TITLE
Display a clear sign-in error message when trying to connect with the same email address using two different sign-in methods

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#708]
## Describe the bug

Fix Google Sign-in when trying to connect with an email address used originally with password-less link sign-in method

## To Reproduce

1.  Sign in to LabelFlow with a google account
4.  See error. Unable to sign in

## Expected behavior

The error message should be more explicit so that the user understands what is going on.
Something like:
> We could not sign you in. If you have already signed in with this email address, try again but using the same sign-in method you originally used. Password-less magic link for instance.

## Screenshots

![image](https://user-images.githubusercontent.com/16015322/147686759-7af01b26-33bd-476f-a683-8a8f77e5a7d4.png)
![image](https://user-images.githubusercontent.com/16015322/147686775-6affc202-09c5-4c9c-bbab-0a63b56f56a3.png)

## Device information

 

- **Device:** 
- **OS:** 
- **Browser:** 
- **Version:**

**Comment by valerian** [comment]
Is it still not working for you? Can't reproduce issue on my side.

**Comment by nicOwlas** [comment]
Just tried again. The error triggers when you try to sign-in with a google email address that has already sign up through email magic link. Can you reproduce?

**Comment by RaynalHugo** [comment]
From https://next-auth.js.org/faq

> **When I sign in with another account with the same email address, why are accounts not linked automatically?**

>Automatic account linking on sign in is not secure between arbitrary providers - with the exception of allowing users to sign in via an email addresses as a fallback (as they must verify their email address as part of the flow).
When an email address is associated with an OAuth account it does not necessarily mean that it has been verified as belonging to account holder — how email address verification is handled is not part of the OAuth specification and varies between providers (e.g. some do not verify first, some do verify first, others return metadata indicating the verification status).
With automatic account linking on sign in, this can be exploited by bad actors to hijack accounts by creating an OAuth account associated with the email address of another user.
For this reason it is not secure to automatically link accounts between arbitrary providers on sign in, which is why this feature is generally not provided by authentication service and is not provided by NextAuth.js.
Automatic account linking is seen on some sites, sometimes insecurely. It can be technically possible to do automatic account linking securely if you trust all the providers involved to ensure they have securely verified the email address associated with the account, but requires placing trust (and transferring the risk) to those providers to handle the process securely.
Examples of scenarios where this is secure include with an OAuth provider you control (e.g. that only authorizes users internal to your organization) or with a provider you explicitly trust to have verified the users email address.
Automatic account linking is not a planned feature of NextAuth.js, however there is scope to improve the user experience of account linking and of handling this flow, in a secure way. Typically this involves providing a fallback option to sign in via email, which is already possible (and recommended), but the current implementation of this flow could be improved on.
Providing support for secure account linking and unlinking of additional providers - which can only be done if a user is already signed in already - was originally a feature in v1.x but has not been present since v2.0, is planned to return in a future release.

**Comment by nicOwlas** [comment]
I've read it and that's fine for now, we said we would not manage the account linking yet. But the error message should be more explicit so that the user understands what is going on.
Something like:
> An account with this email address already exists. Try again using the same sign-in method you originally used.

**Comment by nicOwlas** [comment]
And regarding the email verification, google returns in the token id a field `email_verified`: `true`|`false` that we could use to link accounts or not. [Documentation here.](https://developers.google.com/identity/protocols/oauth2/openid-connect#an-id-tokens-payload). But that will be part of another issue.
