### ISSUE TITLE
Users do not get an error when creating a workspace with an already existing Slug

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#710]
## Describe the bug

Users does not get an error when creating a workspace with an already existing Slug

## To Reproduce

1.  Sign in and create a workspace named "Demo"
2.  You will get an error 400
3. 
4. 

## Expected behavior

Alert the user, this workspace name is already taken.

## Screenshots

![image](https://user-images.githubusercontent.com/16015322/147728521-7c6fa433-eee6-41da-b0fd-f745fa5eac25.png)

![image](https://user-images.githubusercontent.com/16015322/147728429-1f959fe8-687a-4c93-8639-fa12803d65e3.png)

## Device information

 

- **Device:** 
- **OS:** 
- **Browser:** 
- **Version:**

**Comment by bbenoist** [comment]
@nicOwlas Actually, it's already verifying that the slug exists (you can see the details in the console log).
But, as we don't have a standard way to extract the ApolloError message yet, I couldn't display a more meaningful error at the time of writing #667 
This is the problem I've told you duriing one of tthe DSMs. We've created #712 (which I've just converted to an issue) to track this. Would you like me to work on #712 directly?

**Comment by nicOwlas** [comment]
I've see the console details. Hugo had created a resolver `doesWorkspaceSlugExists` (or something like it) which returns a boolean, as an easy fix, can't you use it to display a more meaningful error if it returns `true`?

**Comment by bbenoist** [comment]
This is what I've already used (I've even renamed it `workspaceExists` to get a more obvious name 😉 ).

You had this error message because you've submitted the form before the background call to `workspaceExists` could end (as the verification is debounced and non-blocking).
If you wait before submitting, you'll see that the workspace name verification is working as expected and displays the correct error message.

In other words, the `workspaceExists` verification on the client-side doesn't really prevent you from submitting the form if it is not finished yet (simpler verifications like forbidding special characters are immediate BTW).
If the `workspaceExists` has time to finish before the form could be submitted, it will block the form from being submitted and display a meaningful error message (which is the exact same returned by `createWorkspace` in the `ApolloError` details).
But, if it didn't had enough time before the end-user could submit the form, we delegate the verification responsibility to the server which is in anyway the real source of truth.
This mechanism is made so that the golden path remains as fast as possible. We have actually no reason to wait for `workspaceExists` since it's already done by `createWorkspace`.

**Comment by nicOwlas** [comment]
Understood. Thanks for the explanation. I've seen your draft PR. Good, for now! It will close #712 too or more would need to be done in #712?
