### ISSUE TITLE
Make dataset export work in online workspaces

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#751]
## Is your feature request related to a problem? Please describe

Robustify export, it fails to export labels only in some cases

## Describe the solution you'd like (import visuals when possible)

- [ ] Export generates an .xml file if one image is not found ([example this one](https://labelflow.ai/demo/datasets/tutorial-2/images))
- [ ] For some datasets, example [this one](https://labelflow.ai/omexom-arabie-saoudite/datasets/2018-12-19-dammam-tower-557-type-da_tower-556-type-da-tower-557-type-da-cjptzhu77h6h80790sna6mpjm/images), the export of labels to coco format (not exporting the images, also fails though no images are missing)

## Additional context

Due to remote vs local workspace?

**Comment by nicOwlas** [comment]
Example of dataset leading to an .xml export file when some images are not found: https://labelflow.ai/demo/datasets/tutorial-2/images

**Comment by valerian** [comment]
Currently all exports from workspaces seem to fail actually, even from the simplest datasets (1 image, 1 or 0 labels)

**Comment by valerian** [comment]
While working on this I discovered several issues:
- We store exports on our S3 without tracking and garbage collection
- Instead of directly giving the download URL (from our API), we use that URL to download the data client-side, put it in a blob, and create a local "blob:" URL to download it from:
  - The file must be pre-downloaded locally with no indication of progress, it's fine for JSON, but not for ZIP of big datasets.
  - I guess we do that to avoid exposing a re-usable URL with no expiry date, but in the end we are jumping through hoops and having uncollected "garbage" on our S3 that is only ever used one time.

**Comment by bbenoist** [comment]
@valerian 

> I guess we do that to avoid exposing a re-usable URL with no expiry date, but in the end we are jumping through hoops and having uncollected "garbage" on our S3 that is only ever used one time.

Regardless of [my personal opinion on this](https://labelflow.slack.com/archives/C022PCC0H0W/p1640877399398900?thread_ts=1640865424.377400&cid=C022PCC0H0W), the thing is that we shouldn't have to fear of leaking the "source" URL since bucket-access should be secured 😉
