### ISSUE TITLE
Integrate a Star us on GitHub to the website

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#759]
## Objective
Integrate a Star us on GitHub to the website. Have a call to action similar to supabase.com
![image](https://user-images.githubusercontent.com/16015322/148773404-b0a0b861-12ae-4d65-a1f8-cd394dd3c9fb.png)

## Tasks
- Two options:
  - https://ghbtns.com/
  - https://buttons.github.io/

## End result
Option A - Do not display the count but clear call to action. And triggers curiosity to go to GitHub to see the count
![image](https://user-images.githubusercontent.com/16015322/148774698-b70006cf-c690-4c1e-99cc-50a7a107ca44.png)

Option B - Display the count
![image](https://user-images.githubusercontent.com/16015322/148774792-b1346342-e63a-4f38-b126-61039fdbe3eb.png)

**Comment by nicOwlas** [comment]
Agree, so option A but yes using a Chakra button

**Comment by bbenoist** [comment]
If you want my fair opinion, I don't see the point of changing this button if it's not for displaying the number of stars nor actually starring the project.

The GitHub and Supabase buttons you mention only redirects to a GitHub page. It doesn't stars their project for you.  
It's just the GitHub button we already have but with some text and a star icon instead of the GitHub logo (making it less intuitive IMO).

As said above, if that's for :
* Renaming a button to a name which don't describe correctly what the button is actually doing.
* Taking the risk to make our visitor focus on it instead of our primary income sources.

Then I'd prefer to just keep things simple and don't do anything more with our existing design.

If you really want this change, here are your pull-requests, i've made it so you can choose the one you prefer (or close both as I'd like to 😜): 

## Current version

![image](https://user-images.githubusercontent.com/2091902/148780778-3eb9cac5-1127-4504-a22f-8571a2bd6a92.png)
![image](https://user-images.githubusercontent.com/2091902/148780837-a8c3429b-50a8-4dc1-81f0-3fc54cfdd02d.png)


## Button version

![image](https://user-images.githubusercontent.com/2091902/148781025-2840378c-107d-4a03-ad28-19cbf1b6e8cc.png)
![image](https://user-images.githubusercontent.com/2091902/148779508-c70ba87b-8e55-4b55-b4ae-538ffd6006f2.png)

#761

https://labelflow-git-enhancement-github-star-button-labelflow.vercel.app/website

## Link version

![image](https://user-images.githubusercontent.com/2091902/148781190-fc994040-0b5d-4309-b2be-30ae19e5aa77.png)
![image](https://user-images.githubusercontent.com/2091902/148779707-fb0052a0-713f-4a64-b4d2-f11013ea650f.png)

#760

https://labelflow-git-enhancement-github-star-link-labelflow.vercel.app/website

**Comment by bbenoist** [comment]
I've forgot to mention that I've not changed the icon yet.
Here is how it looks like with it:

## Link version
![image](https://user-images.githubusercontent.com/2091902/148784246-85258ca0-8574-475c-aec2-5a69155549db.png)

## Button version
![image](https://user-images.githubusercontent.com/2091902/148784503-510b0f22-dba0-4571-91a2-0aa3b58ef103.png)

**Comment by bbenoist** [comment]
Please let me know which icon should I use (or if we stay as before and close the PR).

And don't forget that we have already an explicit button on the same page (which would have a different text but the same target):

![image](https://user-images.githubusercontent.com/2091902/148785036-282763a0-63d4-4208-8860-172e8aa1f147.png)

**Comment by nicOwlas** [comment]
Even the non-official Star GitHub buttons are only redirections and they do not allow to directly star a repo. The call to action with this text is clearer than just a logo.
- Link version 👍 
- Icon in header: Star

About the 2nd button, lets keep it like that.
