### ISSUE TITLE
🌶️ Fix the remaining Cypress code based on the SW or Dexie.

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#772]
- [x] golden-path.online.ts
- [x] image-navigation.online.ts
- [x] invitation-manager.online.ts
- [ ] workspace-access.online.ts
- [x] dataset-manipulation.online.ts

blocked by #771 

🌶️ painful | 🍔 needs specs | 🍏 easy | 🍺 fun

**Comment by Jordanlelay** [comment]
## Tests that fails for me locally:
1. dataset-manipulation
1. golden-path
1. invitation-manager
1. workspace-access

### dataset-manipulation

Problem comes from `typescript/web/src/pages/[workspaceSlug]/datasets/index.tsx` at line 46, because  the `workspaceSlug` is `undefined`.

Can be easily fixed by extracting it as follow:

```
const { workspaceSlug } = useWorkspace();
```

### golden-path

2 problems here:

1. Same as in dataset-manipulation, `workspaceSlug` is `undefined`
1. The `WelcomeModal` component is still here. Because we completely removed the service worker code, the test wait endlessly for the `Skip the tutorial` button to appear, which never happens because the test dataset is not loaded anymore.

We should remove or at least rework the `WelcomeModal` to take in account all the changes we are currently making to get rid of the service worker. In my opinion, we should do it before fixing the Cypress tests as several fails are due to it, but after the other issues SW related, possibly in this order:
1. #776 
2. #775 
3. #771 
4. #777 
5.  Finally this one

### invitation-manager

Problem is known but was supposed to be fixed, maybe it's only locally: a `Sign in` button is masked by the sign in modal, which make the test fail

### workspace-access

Same problem as for `golden-path`, not able to `Skip the tutorial`

**Comment by bbenoist** [comment]
Thanks for the details 👏

It's a good thing to have a list of the dependencies! If everyone agree, let's fix the Cypress problems directly within the PR blocking this issue then fix the remaining ones once we've merged all 4 of them.

> #### invitation-manager
> Problem is known but was supposed to be fixed, maybe it's only locally: a Sign in button is masked by the sign in modal, which make the test fail

This should be fixed with #776 since it completely removes the need for a sign-in modal 😉

**Comment by bbenoist** [comment]
Closed by #843
