### ISSUE TITLE
Selecting an image in multiple selection is too slow

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#968]
## Tasks

Test with a set to store the ids with every dataset images. Check if an id is in or out.
Reduce massively sluginess when selecting more than 200 items on a page.

Blocked by #854

**Comment by Jordanlelay** [comment]
After investigating the issue, the way it is implemented today raises several problems:
- A performance issue, as mentioned in this one. The selected images are handled in an array of strings, containing their ids. Each image item depends on the said array, so any change to the array provokes a re-render of every one of them. The use of `useMemo` hook [here](https://github.com/labelflow/labelflow/blob/main/typescript/web/src/components/dataset-images-list/images-list.tsx#L141) or the HOC `memo` [there](https://github.com/labelflow/labelflow/blob/main/typescript/web/src/components/dataset-images-list/image-card.tsx#L272) do not prevent the UI update to be awfully slow. It might be due to the fact that the `selected` array is used in `useSelectedItem`, which is called in `ImageItem`, which wraps `ImageCard`, thus the re-render.
- A UX issue. When we click on "Select all" button, all the images of the current page goes in a selected state, and the button itself shows that every element on the page is selected. If we change page, the selected elements are still in the `selected` array, but the `Select all` button has not changed of state, still showing that everything is selected. That happens because of [this line](https://github.com/labelflow/labelflow/blob/main/typescript/web/src/components/dataset-images-list/images-list.tsx#L49) which only checks if the number of selected elements equals the number of items per page. This button behavior is broken in terms of user experience IMO and should be re-groomed ASAP, we have several options.

**Comment by nicOwlas** [comment]
Regarding the second point, I don't feel the UX is broken. The button is in a selected state yes and clicking on it deselect the selected items on the previous page.

What would be the possible alternatives?
- Empty the list of selected images if one change page.
- Show the button with the partially selected state when all the elements on a page are not selected but there are some selected element?

**Comment by Jordanlelay** [comment]
- You select everything on page 1: button state is `All selected`
- You switch to page 2, nothing is selected but: button state is `All selected`
- You add 1 image on page 2: button state is `Some selected`
- You go back to page 1, everything is selected but: button state is `Some selected`

That's not very intuitive, is it ?

The problem for is that the button behave differently regarding on if you are selecting or deselecting. An example:
- You select everything on page 1 with a click on button `Select all`
- You go to page 2, you select every element somehow
- You click on `Deselect all` button: every item is gone including those on page one.

So the `Select all` button is adding every element **on the current page**, but the `Deselect all` is removing all elements regardless to the page they were on.

For me the alternatives are:
- We deal with selected elements on the current page only, changing page erases selected elements
- We handle the selected elements by page in something like a store

**Comment by nicOwlas** [comment]
Decisions:
- Regarding the UX: Empty the list of selected images if one change page.
- Regarding performances:
  - Array of images + boolean. When the gallery loads: create the table with the ids of the images and initialize the booleans to `false`. If image is selected, change it's boolean to `true`.
  - Have a variable to store the number of selected items
